// using Super;
// namespace Drivas;

// Driver d1 = new("Zack");
// Driver d2 = new("Daniel");
// Driver d3 = new("Kyle");
// Driver d4 = new("Donnie");
// Driver d5 = new("Mo");
// Driver d6 = new("Janna");
// Driver d7 = new("Meme");
// Driver d8 = new("Kylie");
// Driver d9 = new("Logan");
// Driver d10 = new("Emma");
// Driver d11 = new("Chloe");
// Driver d12 = new("Shane");
// Driver d13 = new("Rich");
// Driver d14 = new("Devin");
// Driver d15 = new("Panther");
// Driver d16 = new("Tigar");
// Driver d17 = new("Cat");
// Driver d18 = new("Lion");
// Driver d19 = new("Wolf");
// Driver d20 = new("OgiBoggie");
// Driver d21 = new("Dr D");
// Driver d22 = new("Dr A");
// Driver d23 = new("Nurse Joy");
// race1.AddDriver(d1.Name);
// race1.AddDriver(d2.Name);
// race1.AddDriver(d3.Name);
// race1.AddDriver(d4.Name);
// race1.AddDriver(d5.Name);
// race1.AddDriver(d6.Name);
// race1.AddDriver(d7.Name);
// race1.AddDriver(d8.Name);
// race1.AddDriver(d9.Name);
// race1.AddDriver(d10.Name);
// race1.AddDriver(d11.Name);
// race1.AddDriver(d12.Name);
// race1.AddDriver(d13.Name);
// race1.AddDriver(d14.Name);
// race1.AddDriver(d15.Name);
// race1.AddDriver(d16.Name);
// race1.AddDriver(d17.Name);
// race1.AddDriver(d18.Name);
// race1.AddDriver(d19.Name);
// race1.AddDriver(d20.Name);
// race1.AddDriver(d21.Name);
// race1.AddDriver(d22.Name);
// race1.AddDriver(d23.Name);